# Generated by Django 2.1.4 on 2018-12-25 07:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_markdown.models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181221_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('content', mdeditor.fields.MDTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 25, 7, 43, 1, 363178, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=django_markdown.models.MarkdownField(),
        ),
    ]
